classdef BackendRegistry
    %BACKENDREGISTRY Stable product catalog for video-tracking backends.

    methods (Static)
        function backends = catalog()
            backends = [ ...
                Tracking.BackendRegistry.entry( ...
                    "zephir", "ZephIR", "integrated", true, false, ...
                    "Sparse reference annotations; existing MATLAB/Python workflow."), ...
                Tracking.BackendRegistry.entry( ...
                    "ultrack", "Ultrack", "contract_ready", false, true, ...
                    "Backend-neutral contract ready; worker and segmentation cache remain."), ...
                Tracking.BackendRegistry.entry( ...
                    "hoct", "Higher-Order Transformer", "contract_ready", false, true, ...
                    "Backend-neutral contract ready; worker, weights, and segmentation cache remain.")];
        end

        function backend = find(id)
            backends = Tracking.BackendRegistry.catalog();
            index = find([backends.id] == lower(string(id)), 1);
            if isempty(index)
                error('Tracking:BackendRegistry:UnknownBackend', ...
                    'Unknown tracking backend: %s', char(string(id)));
            end
            backend = backends(index);
        end

        function [names, ids] = uiChoices()
            backends = Tracking.BackendRegistry.catalog();
            names = cellstr([backends.name]);
            ids = cellstr([backends.id]);
        end

        function readiness = inspect(id)
            backend = Tracking.BackendRegistry.find(id);
            readiness = struct( ...
                'backend', char(backend.id), ...
                'ready', backend.runnable, ...
                'summary', '', ...
                'runtime', '');
            if backend.runnable
                readiness.summary = sprintf('%s is integrated.', char(backend.name));
                return
            end

            env_name = sprintf('NEUROPAL_%s_PYTHON', upper(char(backend.id)));
            runtime = strtrim(getenv(env_name));
            readiness.runtime = runtime;
            if isempty(runtime)
                readiness.summary = sprintf( ...
                    '%s contract ready; worker, segmentation, and %s are not configured.', ...
                    char(backend.name), env_name);
            elseif exist(runtime, 'file') ~= 2
                readiness.summary = sprintf('%s points to a missing runtime: %s', ...
                    env_name, runtime);
            else
                readiness.summary = sprintf( ...
                    '%s runtime found; app worker and segmentation adapter still pending.', ...
                    char(backend.name));
            end
        end
    end

    methods (Static, Access = private)
        function value = entry(id, name, status, runnable, requires_segmentation, summary)
            value = struct( ...
                'id', lower(string(id)), ...
                'name', string(name), ...
                'status', string(status), ...
                'runnable', logical(runnable), ...
                'requires_segmentation', logical(requires_segmentation), ...
                'summary', string(summary));
        end
    end
end
