function package = compose_volume(app, raw)
if nargin < 1 || isempty(app)
    app = Program.app;
end
if nargin < 2 || isempty(raw)
    raw = Program.GUIHandling.get_active_volume(app, 'request', 'all');
end

[raw_volume, raw_dims] = Program.Validation.pad_rgb(raw.array);
channel_state = Program.Handlers.channels.processing_state(app);

channels = struct( ...
    'r', Program.Handlers.channels.render_struct_from_row(channel_state.r), ...
    'g', Program.Handlers.channels.render_struct_from_row(channel_state.g), ...
    'b', Program.Handlers.channels.render_struct_from_row(channel_state.b), ...
    'white', Program.Handlers.channels.render_struct_from_row(channel_state.white), ...
    'dic', Program.Handlers.channels.render_struct_from_row(channel_state.dic), ...
    'gfp', Program.Handlers.channels.render_struct_from_row(channel_state.gfp), ...
    'other', {cellfun(@Program.Handlers.channels.other_struct_from_row, ...
        num2cell(channel_state.other), 'UniformOutput', false)});

[render_volume, rgb_channels] = Program.Helpers.compose_display_volume(raw_volume, channels);
threshold_raw = Program.GUIHandling.proc_threshold_raw_value(app, max(render_volume, [], 'all'));
render_volume = Program.Helpers.finalize_display_volume(render_volume, rgb_channels, threshold_raw);

actions = fieldnames(app.flags);
for a = 1:length(actions)
    action = actions{a};
    if app.flags.(action) == 1
        msg = sprintf('Applying %s...', action);
        Program.Handlers.dialogue.step(msg)
        Program.Handlers.loading.start(msg);
        render_volume = Methods.ChunkyMethods.apply_vol(app, action, render_volume);
    end
end

package = struct( ...
    'raw', raw, ...
    'raw_volume', raw_volume, ...
    'raw_dims', raw_dims, ...
    'channels', channels, ...
    'render_volume', render_volume, ...
    'threshold_raw', threshold_raw);
end
