function view = compose_main_display_view(raw_volume, channels, z_gui, is_z_flip, source_key, existing_view, threshold_raw)
%COMPOSE_MAIN_DISPLAY_VIEW Render only a projection and the selected RGB plane.
% source_key identifies the source and its explicit data revision. Callers must
% advance that revision when changing pixels without changing the source path.
% Composition remains slice-wise to preserve the existing source scaling.

if nargin < 6
    existing_view = [];
end
if nargin < 7
    threshold_raw = 0;
end
if isempty(raw_volume)
    view = [];
    return
end

z_count = size(raw_volume, 3);
z_gui = Program.Helpers.gui_z_to_data_index(z_gui, z_count, false);
z_data = Program.Helpers.gui_z_to_data_index(z_gui, z_count, is_z_flip);
signature = struct( ...
    'source', source_key, ...
    'raw_size', size(raw_volume), ...
    'raw_class', class(raw_volume), ...
    'channels', channels, ...
    'gfp_color', Program.GUIPreferences.instance().GFP_color, ...
    'threshold_raw', threshold_raw);

if local_can_reuse_projection(existing_view, signature)
    view = existing_view;
    view.projection_cache_hit = true;
    view.slice_cache_hit = isequal(view.z_data, z_data);
    view.composed_slices = 0;
    if ~view.slice_cache_hit
        slice_rgb = local_compose_slice(raw_volume, channels, z_data);
        view.display_slice = local_finalize_plane( ...
            slice_rgb, view.rgb_channels, threshold_raw, view.volume_max);
        view.composed_slices = 1;
    end
    view.is_z_flip = logical(is_z_flip);
    view.z_gui = z_gui;
    view.z_data = z_data;
    return
end

max_projection = [];
selected_slice = [];
volume_max = 0;
rgb_channels = {};
for z = 1:z_count
    Program.Handlers.dialogue.step(sprintf('Rendering z-slice %d of %d...', z, z_count));
    [slice_rgb, rgb_channels] = local_compose_slice(raw_volume, channels, z);
    if isempty(max_projection)
        max_projection = slice_rgb;
    else
        max_projection = max(max_projection, slice_rgb);
    end
    if z == z_data
        selected_slice = slice_rgb;
    end
    volume_max = max(volume_max, double(max(slice_rgb, [], 'all')));
end

% The same global maximum is used for both planes. Finalization is pointwise
% with explicit gamma/window values, so it does not require a rendered stack.
max_projection = local_finalize_plane( ...
    max_projection, rgb_channels, threshold_raw, volume_max);
display_slice = local_finalize_plane( ...
    selected_slice, rgb_channels, threshold_raw, volume_max);
view = struct( ...
    'renderer', 'main_display_view', ...
    'schema_version', 2, ...
    'target', 'main', ...
    'signature', signature, ...
    'channels', channels, ...
    'rgb_channels', {rgb_channels}, ...
    'threshold_raw', threshold_raw, ...
    'is_z_flip', logical(is_z_flip), ...
    'raw_size', size(raw_volume), ...
    'z_gui', z_gui, ...
    'z_data', z_data, ...
    'volume_max', volume_max, ...
    'max_projection', max_projection, ...
    'display_slice', display_slice, ...
    'projection_cache_hit', false, ...
    'slice_cache_hit', false, ...
    'composed_slices', z_count);
end

function tf = local_can_reuse_projection(view, signature)
tf = isstruct(view) && isscalar(view) && ...
    all(isfield(view, {'renderer', 'schema_version', 'signature', ...
        'max_projection', 'display_slice', 'volume_max', 'rgb_channels', 'z_data'})) && ...
    strcmp(char(string(view.renderer)), 'main_display_view') && ...
    isequal(view.schema_version, 2) && ...
    ~isfield(view, 'render_volume') && ...
    isequaln(view.signature, signature) && ...
    ~isempty(view.max_projection) && ~isempty(view.display_slice) && ...
    isfinite(view.volume_max);
end

function [slice_rgb, rgb_channels] = local_compose_slice(raw_volume, channels, z_data)
raw_slice = raw_volume(:, :, z_data, :);
raw_slice = reshape(raw_slice, size(raw_volume, 1), size(raw_volume, 2), 1, size(raw_volume, 4));
[slice_rgb, rgb_channels] = Program.Helpers.compose_display_volume(raw_slice, channels);
end

function plane = local_finalize_plane(plane, rgb_channels, threshold_raw, volume_max)
plane = Program.Helpers.finalize_display_volume(plane, rgb_channels, threshold_raw, volume_max);
% Keep spatial singleton dimensions: squeeze would swap Y/X for a 1-pixel axis.
plane = reshape(plane, size(plane, 1), size(plane, 2), 3);
end
