function test_open_callback_contract()
%TEST_OPEN_CALLBACK_CONTRACT Guard the interactive-open package boundary.

repo_root = fileparts(fileparts(mfilename('fullpath')));
open_source = fileread(fullfile(repo_root, '+Program', '+Routines', 'open.m'));
processing_source = fileread(fullfile( ...
    repo_root, '+Program', '+Routines', '+Processing', 'load_file.m'));

assert(~contains(open_source, 'app.UnselectNeuron('), ...
    ['Program.Routines.open must use Program.Handlers.neurons instead of ' ...
     'calling the app''s private UnselectNeuron method.']);
assert(~contains(open_source, 'app.SaveIDToFile('), ...
    ['Program.Routines.open must not call the app''s private ' ...
     'SaveIDToFile method.']);
assert(contains(open_source, 'onCleanup(@() local_finish_open(app))'), ...
    'Program.Routines.open must release is_opening_file after callback errors.');
assert(~contains(processing_source, 'app.ProcCropImageButtonPushed('), ...
    ['Processing.load_file must use the public crop routine instead of ' ...
     'calling the app''s private crop callback.']);

fprintf('OPEN_CALLBACK_CONTRACT=PASS\n');
end
