classdef MethodRegistry
    %METHODREGISTRY Product-facing catalog of detection and identity methods.
    %
    % Benchmark experiments change faster than the desktop application. This
    % registry is the stable boundary: only runnable entries are offered in
    % the UI, while scaffolded entries retain their contracts and evidence for
    % the next adapter without pretending that they are available.

    methods (Static)
        function methods = catalog()
            methods = [ ...
                Methods.MethodRegistry.entry( ...
                    "mp", "detection", "Matching pursuit", "legacy", true, ...
                    "volume_rgbw", "centroids_yxz", ...
                    "Fast MATLAB baseline; useful when Python models are unavailable."), ...
                Methods.MethodRegistry.entry( ...
                    "nn", "detection", "Neural network", "legacy", true, ...
                    "volume_rgbw", "centroids_yxz", ...
                    "Bundled legacy neural detector."), ...
                Methods.MethodRegistry.entry( ...
                    "cellpose", "detection", "Cellpose", "adapter", true, ...
                    "volume_rgbw", "centroids_yxz_and_masks", ...
                    "Runnable when a compatible local Cellpose model is configured."), ...
                Methods.MethodRegistry.entry( ...
                    "yolo", "detection", "YOLO", "recommended_portable", true, ...
                    "volume_rgbw", "centroids_yxz_and_box_summary", ...
                    "Portable benchmarked detector; held-out F1@5um 0.7117."), ...
                Methods.MethodRegistry.entry( ...
                    "spotiflow_supervised", "detection", "Spotiflow", "recommended_portable", true, ...
                    "volume_rgbw", "centroids_xyz_with_scores", ...
                    "Frozen four-view detector; validation mean F1@3/6um 0.9233."), ...
                Methods.MethodRegistry.entry( ...
                    "detection_moe", "detection", "Accurate ensemble", "scaffolded", false, ...
                    "volume_rgbw", "centroids_xyz_with_scores", ...
                    "Locked Spotiflow/YOLO/nnU-Net ensemble; locked-test F1@6um 0.9233."), ...
                Methods.MethodRegistry.entry( ...
                    "anshita_gat", "identity", "GAT", "recommended", true, ...
                    "detected_centroids_rgbw", "ranked_identity_predictions", ...
                    "Primary app auto-ID adapter; benchmark top-5 0.9382 on the geometry run."), ...
                Methods.MethodRegistry.entry( ...
                    "legacy_atlas", "identity", "Atlas", "legacy", true, ...
                    "detected_centroids_rgb", "ranked_identity_predictions", ...
                    "Bundled MATLAB alignment and atlas-likelihood fallback."), ...
                Methods.MethodRegistry.entry( ...
                    "crf_cellid_2", "identity", "CRF", "adapter_ready", true, ...
                    "detected_centroids_rgbw", "ranked_identity_predictions", ...
                    "Strongest locked benchmark row; top-1 0.8128 and top-5 0.9550."), ...
                Methods.MethodRegistry.entry( ...
                    "wormnd_atlas", "identity", "WormND atlas assignment", "deferred", false, ...
                    "detected_centroids_rgbw", "ranked_identity_predictions", ...
                    "Useful native-reference method, but its aligned-atlas assets are not portable yet.")];
        end

        function methods = list(task, varargin)
            parser = inputParser;
            addParameter(parser, 'RunnableOnly', false, ...
                @(value) islogical(value) && isscalar(value));
            parse(parser, varargin{:});

            methods = Methods.MethodRegistry.catalog();
            task = string(task);
            keep = [methods.task] == task;
            if parser.Results.RunnableOnly
                keep = keep & [methods.runnable];
            end
            methods = methods(keep);
        end

        function method = find(id)
            methods = Methods.MethodRegistry.catalog();
            index = find([methods.id] == string(id), 1);
            if isempty(index)
                error('Methods:MethodRegistry:UnknownMethod', ...
                    'Unknown method registry ID: %s', char(string(id)));
            end
            method = methods(index);
        end

        function [items, ids] = uiChoices(task)
            methods = Methods.MethodRegistry.list(task, 'RunnableOnly', true);
            items = cellstr([methods.name]);
            ids = cellstr([methods.id]);
        end

        function text = evidence(id)
            method = Methods.MethodRegistry.find(id);
            text = char(method.evidence);
        end
    end

    methods (Static, Access = private)
        function value = entry(id, task, name, status, runnable, input_contract, output_contract, evidence)
            value = struct( ...
                'id', string(id), ...
                'task', string(task), ...
                'name', string(name), ...
                'status', string(status), ...
                'runnable', logical(runnable), ...
                'input_contract', string(input_contract), ...
                'output_contract', string(output_contract), ...
                'evidence', string(evidence));
        end
    end
end
